### ISSUE TITLE
CRUD Users

### ISSUE THREAD

**Issue by Enapreev** [jerowe/ella-admin#1]
As the admin, I should be able to create a user setting up the following details:
- Email
- Password

**Comment by Enapreev** [comment]
@jerowe I would like to find out regarding the password:
- The admin set up the password manually for the new users, or
- The new users receive the email with the link to set the pass on their own, or
- The users receive the email with autogenerated pass

Which one do you prefer?

**Comment by jerowe** [comment]
Option 2 or 3 is fine.

**Comment by Enapreev** [comment]
@jerowe we actually combined options 2 and 3) the newly created user will have his password autogenerated and will receive the email with the link to reset his pass
Oleg is finishing tests here so this is 99% done

**Comment by Enapreev** [comment]
done
