### ISSUE TITLE
CRUD User Groups

### ISSUE THREAD

**Issue by Enapreev** [jerowe/ella-admin#2]
As the admin, I should be able to CRUD User Groups with the following details:
- Group name
- Assigned users
- Assigned gene pannels

**Comment by Enapreev** [comment]
@jerowe a couple of questions here:
- should users be able to CRUD user groups as well?
- should users be able to join and leave user groups on their own?
- should users be able to invite other users to their groups?

**Comment by jerowe** [comment]
> should users be able to CRUD user groups as well?
> should users be able to join and leave user groups on their own?
> should users be able to invite other users to their groups?

No only admins.

**Comment by Enapreev** [comment]
Done
